### ISSUE TITLE
setting parameter for a vector parameter

### ISSUE THREAD

**Issue by MohammadHadiAlizadeh** [OpenModelica/OMMatlab#16] opened 2022-10-01 13:49 UTC
Hello,
I defined a vector parameter in my OM model like this:
`parameter Real[10] a`
But when I try to set the parameters with OMMatlab command, I'm getting an error
`omc.setParameters("a[1:10]=[1,1,1,1,1,1,1,1,1,1]")`

what is the correct way to set a vector parameter with OMMatlab?

**Comment by arun3688** [comment] 2022-10-02 15:40
@MohammadHadiAlizadeh The correct way is given below

```
>>> omc.getParameters()
{'x[1]': '1.0', 'x[2]': '2.0'}
>>> omc.setParameters("x[1]=3")
>>> omc.getParameters()
{'x[1]': '3', 'x[2]': '2.0'}
```

**Comment by MohammadHadiAlizadeh** [comment] 2022-10-03 07:47
> @MohammadHadiAlizadeh The correct way is given below
> 
> ```
> >>> omc.getParameters()
> {'x[1]': '1.0', 'x[2]': '2.0'}
> >>> omc.setParameters("x[1]=3")
> >>> omc.getParameters()
> {'x[1]': '3', 'x[2]': '2.0'}
> ```

I'm getting the following result:

```
>> omc.getParameters()

ans = 

  struct with fields:

    a_1_: '1.0'
    a_2_: '2.0'
       b: '0.0'

>> omc.setParameters("a[1]=5")
a[1] is not a parameter
>> omc.setParameters("a_1_=5")
Error using struct2table (line 33)
Input structure must be a scalar structure, or a structure array with one column or one row.

Error in OMMatlab/getQuantities (line 360)
                result=struct2table(tmpresult,'AsArray',true);

Error in OMMatlab/isParameterChangeable (line 483)
            q = getQuantities(obj, name);

Error in OMMatlab/setParameters (line 469)
                        if isParameterChangeable(obj, value(1), value(2))
 ```


Also this is my OM Model:

```
model dysym
parameter Real[2] a={1,2};
parameter Real b;

Real v;
Real u;


equation


der(v)= 3e-5*u+4e-5*v+10;
0=u-a[2]*v;

initial equation

v=b;


end dysym;
```

**Comment by arun3688** [comment] 2022-10-03 09:51
@MohammadHadiAlizadeh This is true, the problem is,  Matlab does not allow `a[1]` to be a valid key in `struct` and that is the problem , and hence we create a temporary name ` a_1_ ` which should indeed map to original variable `a[1]` which is a bug here, I  will fix this bug

**Comment by arun3688** [comment] 2022-10-03 10:43
@MohammadHadiAlizadeh The issue is fixed now with this commit, 68967a372915c2522ed1f379573984c34c62f4d0, Please do a git pull and test the changes,  I tested the changes 

```
>> omc.getParameters()

ans = 

  struct with fields:

    x_1_: '1.0'
    x_2_: '2.0'

>> omc.setParameters("x_1_=5.0")
>> omc.getParameters()

ans = 

  struct with fields:

    x_1_: "5.0"
    x_2_: '2.0'

```

**Comment by MohammadHadiAlizadeh** [comment] 2022-10-03 15:22
> @MohammadHadiAlizadeh This is true, the problem is, Matlab does not allow `a[1]` to be a valid key in `struct` and that is the problem , and hence we create a temporary name `a_1_` which should indeed map to original variable `a[1]` which is a bug here, I will fix this bug

I'd be grateful if you could fix this bug so that we can change the value of  n*n array parameters. Or even if we can pass the values in a way like ``"a=[1 2; 3 4]"``(which is a 2D array).  
Actually, My M.Sc Project feasibility depends on the capability of OMMATLAB to change array parameters in OpenModelica because this ability empowers us to implement Modern control algorithms on complicated physical systems Modeled in OM.

Many thanks for considering my request.

**Comment by MohammadHadiAlizadeh** [comment] 2022-10-03 15:48
> @MohammadHadiAlizadeh The issue is fixed now with this commit, [68967a3](https://github.com/OpenModelica/OMMatlab/commit/68967a372915c2522ed1f379573984c34c62f4d0), Please do a git pull and test the changes, I tested the changes
> 
> ```
> >> omc.getParameters()
> 
> ans = 
> 
>   struct with fields:
> 
>     x_1_: '1.0'
>     x_2_: '2.0'
> 
> >> omc.setParameters("x_1_=5.0")
> >> omc.getParameters()
> 
> ans = 
> 
>   struct with fields:
> 
>     x_1_: "5.0"
>     x_2_: '2.0'
> ```

Thanks so much.

I tested it :
```
>> omc.setParameters("a_1_1_=8")
>> omc.getParameters()

ans = 

  struct with fields:

    a_1_1_: "8"
    a_1_2_: '2.0'
    a_2_1_: '3.0'
    a_2_2_: '4.0'
         b: '0.0'
```

Nevertheless, one more question: When I try to change a_1_1_ with the set command and use the "get" command to get the value, it returns a string format "8", though the others are char type '8'. Is it normal?

**Comment by arun3688** [comment] 2022-10-03 15:54
@MohammadHadiAlizadeh , I think it should not be an issue

**Comment by MohammadHadiAlizadeh** [comment] 2022-10-04 16:37
@arun3688  Many thanks for your help.

I tried formulating an optimization problem in Matlab to optimize some parameters in My Open Modelica model.

I used `omc.setParameters("Kc=5.00000000852332")` and also checked it with `omc.getParameters("Kc")` and everything were ok.
but when I used `omc.simulate()` and checked the results, the solutions were physically odd! When I checked the Kc parameter with `omc.getSolutions("Kc")`, it returned Kc=5 without any decimals!! Actually,  I think Sth removes decimals and makes the simulation physically wrong!  I'd be grateful if you could help me

this is my om model
```
model tank3

parameter Real Cv=2;


parameter Real A1=0.1;
parameter Real A2=0.1;

parameter Real qibar=1;

parameter Real A3=1;
parameter Real hsp=0.25;

parameter Real Kc;
parameter Real Ti;




parameter Real h1_In;
parameter Real h2_In;
parameter Real h3_In;
parameter Real Flimit_In;
parameter Real I_In;
parameter Real J_In;

Real qo1;
Real qo2;
Real qo3;
Real qd;
Real qi;
Real h1;
Real h2;
Real h3;
Real Flimit;
Real I;
Real J;
Real e;

initial equation
h1=0.25;
h2=0.25;
h3=0.25;
Flimit=0;
J=0;
I=0;


equation
qi=qibar+Kc*(e+1/Ti*I);
qo1=Cv*sqrt(h1);
qo2=Cv*sqrt(h2); 
qo3=Cv*sqrt(h3);
qd=1;
der(h1)=(qi+qd-qo1)/A1;
der(h2)=(qo1-qo2)/A2  ;
der(h3)=(qo2-qo3)/A3  ; 
der(Flimit)=max(0,-qi);
e=hsp-h3;
der(J)=e^2;
der(I)=e;


end tank3;
```

**Closed as completed** 2022-10-04 17:03 UTC
