### ISSUE TITLE
Boosting Linearization Process

### ISSUE THREAD

**Issue by MohammadHadiAlizadeh** [OpenModelica/OMMatlab#26] opened 2023-03-05 13:57 UTC
Hello,

Is there any way to boost the ``omc.linearize()`` process?  I'm attaching a sample file. 
[smp.zip](https://github.com/OpenModelica/OMMatlab/files/10891957/smp.zip)

It takes 6 minutes on my computer to do the linearization process for a single iteration, but I need this process to run 20000 iterations in a for loop with different start values which is very time-consuming(around 97 days!!).  Does any specific flag or method exist for refining the procedure not only for linearization but also for simulation?

**Comment by casella** [comment] 2023-03-06 00:03
I guess the problem is that the model is re-compiled again each time. We should have a way to re-run the compiled executable. This probably requires some overhaul of the entire interface. @adrpo, @sjoelund, @adeas31, what do you think?

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-06 06:52
I can see Clang running again on each iteration. Maybe It is the case!

**Comment by sjoelund** [comment] 2023-03-06 07:55
> We should have a way to re-run the compiled executable

We do. Just not in OMMatlab, I guess

**Comment by arun3688** [comment] 2023-03-06 08:33
@sjoelund Yes that is true, OMMatlab always builds the model, for `simulate` API we use the `executable` for simulation and not for the linearization, May be the I should build the model only once and see if the executable exists, I should not build the model again

**Comment by casella** [comment] 2023-03-06 09:31
> @sjoelund Yes that is true, OMMatlab always builds the model, for `simulate` API we use the `executable` for simulation and not for the linearization, May be the I should build the model only once and see if the executable exists, I should not build the model again

This is potentially dangerous, because it changes the semantics of the simulate() fucntion; one may have built scripts assuming that `simulate()` actually recompiles the code and takes into account all changes you may have applied to it, and such a change would break it.

I think for handlig these cases one should first call `buildModel()` to build the simulation executable from the Modelica sources, and then we should add an extra input `buildModel` with default value `true` to the `simulate()` and `linearize()` functions, so you can call them with buildModel=false and reuse the existing built simulation model.

What do you think?

BTW, the [buildModel()](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html#buildmodel) and [simulate()](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html#simulate) API function calls have no explanation in the User's Guide, which is kind of weird, since they are arguably the most used functions.

**Comment by arun3688** [comment] 2023-03-06 09:51
@casella the `ModelicaSystem("a.mo", "a")` constructor calls the `buidModel()`internally and generates the init.xml and the executable, the `simulate() ` API uses the executable generated by `buildModel()` and overrides all the runtime parameters which users changed and runs the simulation,  the sequence is 

```
ModelicaSystem("a.mo", a) // internally uses the `buildModel()` API
simulate()
``` 



The linearization always calls the `linearize()` API and builds the model which generates the `linearized_model.mo` file and while in loop this takes very long time,  I guess this should directly use the simulation executable and use the runtime flag `-l` to linearize the model and this should speed the process, but i am not sure whether it will generate the linearized_model_init.xml file, because i need to parse the file to get the matrices `A,B,C,D`

**Comment by casella** [comment] 2023-03-07 00:07
> @casella the `ModelicaSystem("a.mo", "a")` constructor calls the `buidModel()`internally and generates the init.xml and the executable, the `simulate() ` API uses the executable generated by `buildModel()` and overrides all the runtime parameters which users changed and runs the simulation, the sequence is
> 
> ```
> ModelicaSystem("a.mo", a) // internally uses the `buildModel()` API
> simulate()
> ```

OK, sorry, I thought it was the same as the interactive environment API.

> The linearization always calls the `linearize()` API and builds the model which generates the `linearized_model.mo` file and while in loop this takes very long time, I guess this should directly use the simulation executable and use the runtime flag `-l` to linearize the model and this should speed the process

Yes

> but i am not sure whether it will generate the linearized_model_init.xml file, because i need to parse the file to get the matrices `A,B,C,D`

Not sure about that either, I normally use the linearize() API from the interactive enviroment and have it generate a matlab or python file to build the linearized object. I guess you need to try that out.

**Comment by arun3688** [comment] 2023-03-13 14:09
@MohammadHadiAlizadeh I made some performance improvements, we now use the simulation executable and perform the linearization which is very fast now, but still getting the matrices A, B, C and D is taking too long time because of building the `buildModel(linearized_model.mo)`,  I don't know how can we avoid this operation, because we have to do this and this generates the .xml file where I read the matrices values and put the results back. 
 With this improvement in my computer it takes `224 seconds` to complete which is less than 4 minutes, some improvements from earlier(6 minutes). But also i see that if you want to make 20000 iteration you must consider using parallelization, i see in matlab there `parfor` which parallelize the for loop,

 but still this needs to be done carefully you have to create a seperate working directory for each iteration and each iterations have their own resources for example, the simulation executable and init.xml file I guess,  you should do something like below

```
parfor i = 1:10
   // copy all the resources from workdirectory to temp directory
   tempdir = mkdir(tempname)
   copyfile(omc.getWorkDirectory(), tempdir)
   omc.linearize()
end
```
@casella is there some other way where we can speed up this building of `linearized_model.mo`, please see the attached file and check how much time it takes for you , you can load this model in OMEdit
[linearized_model.zip](https://github.com/OpenModelica/OMMatlab/files/10958190/linearized_model.zip)

**Comment by casella** [comment] 2023-03-13 14:58
@arun3688 when I perform the linearization I am usually employing a script such as
```modelica
loadFile("MyModel.mo");getErrorString();
setCommandLineOptions("--linearizationDumpLanguage=matlab");getErrorString()
linearize(MyModel, stopTime = 30);getErrorString()
```
and then I retrieve the generated .m file from the file system. I understand that the executable can be built once and run many times. If you do it sequentially, I don't see much of a problem:
1. build the executable file
2. set the model parameters
3. run linearize
4. retrieve the ABCD matrices
5. if not finished then goto 2

Doing the linearization takes the same time as doing the simulation. If that is only a few seconds, 1000 runs will require 20 minutes, no big deal. No need to do it in parallel.

If you really want to do it in parallel, you have to be careful not to overwrite stuff. One option is to use the simulation parameters to change the working directory for each instance, and copy + modify the init.xml file into each of the. But that would generate 1000 directories on the file system, not sure this is really a good idea.

Another option is to have one working directory for each thread. I'm not too familiar with MATLAB parallel programming, maybe you can elaborate on that.

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-13 15:36
@arun3688 

Thanks for the improvements.
As you mentioned, the linearization process with the executable file is fast, but generating `.mo` takes too long.

I don't think parallelization works in my case since my (i+1) iteration needs the data from the (i) iteration((for re-initialization). In other words, the current iteration needs the final data of the previous time step.

Is it possible to generate a (`.mat`) file containing A, B, C, and D matrices directly as the output of `linearize.cpp`? 

Or can the`"--linearizationDumpLanguage=matlab"` flag help, as @casella  mentioned? I think it generates a `.m` file instead of a `.mo` file.

**Comment by arun3688** [comment] 2023-03-13 15:40
> Doing the linearization takes the same time as doing the simulation. If that is only a few seconds, 1000 runs will require 20 minutes, no big deal. No need to do it in parallel.

Yes, Atleast for the model provided by @MohammadHadiAlizadeh It takes compilation time of about 45 secs i guess with API `linearize()` So that is cut down now, i directly use the simulation executable and runtime simulation flags `"-l"` something like this  ` ./a.xe -l 0 ` may be 5 to 10 secs i guess.



> Doing the linearization takes the same time as doing the simulation. If that is only a few seconds, 1000 runs will require 20 minutes, no big deal. No need to do it in parallel.

The linearization does not takes much time, but getting the linear matrices via the API, is taking too much long time, obviously we have the generated file, but reading the generated file is like text processing so that is the reason i am building the generated linearized_mo file

```
loadFile("linearized_model.mo");
buildModel(linearized_model) // this takes more than 2 minutes and this is the problem 
```
the buildModel generates the xml and i read the matrices value from there

**Comment by arun3688** [comment] 2023-03-13 15:43
> As you mentioned, the linearization process with the executable file is fast, but generating `.mo` takes too long.
Generating the '.mo' file does not takes time, building the generated '.mo' file using `buildModel()` takes more time more than 2 minutes  and to read the matrices value from the xml some time. 

As you said parallelization is not possible, the problem is when u use the `linearize() ` API you get A, B, C, D matrices as ouput,I hope you use those datas for next iteration ?

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-13 15:47
> > As you mentioned, the linearization process with the executable file is fast, but generating `.mo` takes too long.
> > Generating the '.mo' file does not takes time, building the generated '.mo' file using `buildModel()` takes more time more than 2 minutes  and to read the matrices value from the xml some time.
> 
> As you said parallelization is not possible, the problem is when u use the `linearize() ` API you get A, B, C, D matrices as ouput,I hope you use those datas for next iteration ?

@arun3688   I use them for designing observer in the current iteration, also I use them as the prediction model for the next iteration :) A little bit complex control algorithm...

**Comment by arun3688** [comment] 2023-03-13 15:54
> I use them for designing observer in the current iteration, also I use them as the prediction model for the next iteration :) A little bit complex control algorithm..

So you need those values right ? for your algorithm

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-13 15:56
> > I use them for designing observer in the current iteration, also I use them as the prediction model for the next iteration :) A little bit complex control algorithm..
> 
> So you need those values right ? for your algorithm

@arun3688  Yes, I need A, B, C, and D matrices right after the `omc.linearize()` attribute.

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-13 16:05
@arun3688 
Also, we should keep `omc.getLineaStates/Outputs/Inputs` attributes working.

**Comment by arun3688** [comment] 2023-03-13 16:32
> Also, we should keep `omc.getLineaStates/Outputs/Inputs` attributes working.

This is the main issue here right now, to get these API work, we need to build the model, obviously when model is generated you already have the matrices in the .mo file, So if you think you will not use the above 4 API your iteration can be done very faster

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-13 16:41
> > Also, we should keep `omc.getLineaStates/Outputs/Inputs` attributes working.
> 
> This is the main issue here right now, to get these API work, we need to build the model, obviously when model is generated you already have the matrices in the .mo file, So if you think you will not use the above 4 API your iteration can be done very faster

@arun3688  I need `omc.getLineaStates/Outputs/Inputs` only once in the first iteration. The names won't change during the simulation, so I can use the name vectors as equal as first iteration.  Can you please create another Method like `omc.FastLineariz` and keep `omc.linearize` too?  So I can pick the names only once at the first iteration from `omc.linearize` results and use them during whole simulation runtime. But for other iterations, I will use `omc.FastLinearize` to get A, B,C and D values without supporting getting the name vectors.

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-13 16:48
Or even I think it can be so that the `.mo` file will be generated only when the user summons `` omc.getLinearNames``.

**Comment by arun3688** [comment] 2023-03-13 16:50
> Or even I think it can be so that the `.mo` file will be generated only when the user summons ` omc.getLinearNames`.

No the .mo file is generated when you use the API, `omc.linearize()` , and the generalized .mo file contains the matrices A,B,C and D.

**Comment by arun3688** [comment] 2023-03-13 17:00
> I need `omc.getLineaStates/Outputs/Inputs` only once in the first iteration. The names won't change during the simulation, so I can use the name vectors as equal as first iteration. Can you please create another Method like `omc.FastLineariz` and keep `omc.linearize` too? So I can pick the names only once at the first iteration from `omc.linearize` results and use them during whole simulation runtime. But for other iterations, I will use `omc.FastLinearize` to get A, B,C and D values without supporting getting the name vectors.

No this will not work, because the time consuming process is getting the matrices A,B, C and D and i am pretty sure for every iteration the value of A,B,C and D will be changed and the `omc.getLinearStates/Names/Inputs and Outputs` is not time consuming. the process goes this 

res = omc.linearize() // linear model is created ".mo" file which contains the matrices A,B, C and D
the res contains 4 matrices, inorder for the values to appear in the `res`, we cannot directly parse the .mo file to get the matrix A, B, C and D, such a parsing is not implemented in OMMAtlab, So the proper way is buiding the generated `linearized_model.mo` using
` buildModel(linearized_model)` more time consuming which will read the matrix values from the generated xml

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-13 17:19
@arun3688 
Yes, you are right. Matrices change in each iteration.
 So you mean we may need another parser, so as the linearized.mo file is treated as a `` .txt`` file, and the matrices are extracted by text-mining techniques.
 I'm thinking whether it is possible to read the ``linearized.mo``  file as a text file and use [newStr = extractBetween(str,startPos,endPos)](https://www.mathworks.com/help/matlab/ref/extractbetween.html) command in Matlab to extract a sub-string between ``A[n,n]=[`` (start) and ``  ];`` (end identifier) then convert it to a numerical matrice as the A, and a sub-string between`` B[m,n]=[`` and ``];`` for calculating B and so on.

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-13 18:33
@arun3688 

I made an script and tested it to parse ``.mo`` file directly in Matlab (I tested on your attached``linearized_model.mo`` file)

```
fileID = fopen('linearized_model.mo','r');
tmp = fscanf(fileID,'%s');
fclose(fileID);
%% Parse A
startPat='parameterRealA[n,n]=';
endPat='];';
newStr = extractBetween(tmp,startPat,endPat);

tp=strcat("A=",newStr,"];"); % forming a Matlab command to be executed to get A
eval(tp); % execute tp command % can be deleted in case of need for string output


%% Parse B
startPat='parameterRealB[n,m]=';
endPat='];';
newStr = extractBetween(tmp,startPat,endPat);

tp=strcat("B=",newStr,"];");
eval(tp);

%% Parse C
startPat='parameterRealC[p,n]=';
endPat='];';
newStr = extractBetween(tmp,startPat,endPat);

tp=strcat("C=",newStr,"];");
eval(tp);

%% Parse D
startPat='parameterRealD[p,m]=';
endPat='];';
newStr = extractBetween(tmp,startPat,endPat);

tp=strcat("D=",newStr,"];");
eval(tp);

```

can you please implement a new method `` omc.FastLinearize``  according to my script? so we can preserve ``omc.linearize()`` too, in order for getting name vectors in the first iteration.

**Comment by arun3688** [comment] 2023-03-13 19:12
@MohammadHadiAlizadeh sure i will implement this

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-13 20:02
@arun3688 

Here is the function

```
function [A,B,C,D] = FastLinearize_Parser(File_Loc)

% File_Loc is the location of file in cell for mat 
%File_Loc='F:\Parser\linearized_model.mo'


fileID = fopen(File_Loc,'r');
tmp = fscanf(fileID,'%s');
fclose(fileID);
%% Parse A
startPat='parameterRealA[n,n]=';
endPat='];';
newStr = extractBetween(tmp,startPat,endPat);

tpA=strcat(newStr,"];"); % forming a Matlab command to be executed to get A
A=eval(tpA); % execute tp command


%% Parse B
startPat='parameterRealB[n,m]=';
endPat='];';
newStr = extractBetween(tmp,startPat,endPat);

tpB=strcat(newStr,"];");
B=eval(tpB);

%% Parse C
startPat='parameterRealC[p,n]=';
endPat='];';
newStr = extractBetween(tmp,startPat,endPat);

tpC=strcat(newStr,"];");
C=eval(tpC);

%% Parse D
startPat='parameterRealD[p,m]=';
endPat='];';
newStr = extractBetween(tmp,startPat,endPat);

tpD=strcat(newStr,"];");
D=eval(tpD);
end
```

**Comment by adrpo** [comment] 2023-03-13 20:52
I don't get this, can't we directly generate Matlab? 
Aren't we already doing this? 
Seems a bit strange to parse the linearized_model.mo file to get the matrices.

**Comment by arun3688** [comment] 2023-03-13 22:00
@adrpo Yes we can generate the matlab version of the linearized model, but for the API 
```
getLinearStates()  // all variables in the model starts with x_
getLinearInputs() // all variables in the model starts with u_
getLinearOutputs() // all variables in the model starts with y_
```
We need to parse the model or build the linearized model to generate the xml file and get those values, but for this case the 
`buildModel(linearized_model)` is taking too much time

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-14 07:56
@arun3688 
There is also a little bug in the omc.linearize() method too. It generated when you optimized the runtime process with``-l`` flag.

It does not consider simulation options, ``stopTime``, for example.

In this tiny model:
```
model nnl


Real x;
Real y;
output Real z;
input Real u;


initial equation


x=1;
y=1;


equation

der(x)=sin(x)+u^2;  //  0.5403 (x-1) + 2 (u-1) +
der(y)=y^0.1+u^4;   // 0.1* (x-1) + 4 (u-1) +
z=x+y;

end nnl;

```

and, for Matlab code:

```
clear all
import OMMatlab.*
tic
omc= OMMatlab();
omc.ModelicaSystem("nnl.mo","nnl");

omc.setInputs("u=1")

%omc.setLinearizationOptions(["stopTime=0"])
omc.setLinearizationOptions(["stopTime=1"])
a=omc.linearize()

A= cell2mat(a(1));
%[A,B,C,D]=omc.FastLinearize();


toc

```

When the stop time changes from 0 to 1, the matrices must change but it does not happen. It always returns the value for stopTime=0.

**Comment by arun3688** [comment] 2023-03-14 08:03
@MohammadHadiAlizadeh no it is not bug the API is changed slightly when we use the runtime Option, so there is an argument called `FastLinearize(obj, lintime, simflags)`, in the function you see the argument lintime which specifies at which time point the linearization should be performed the default time is 0, So you have to specify something like this

`omc.FastLinearize("1");
`
then the runtime flag  will be adapted with -l=1

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-14 08:06
@arun3688  Thanks.
So I can specify linearization tolerance too?

**Comment by arun3688** [comment] 2023-03-14 08:11
> So I can specify linearization tolerance too?

Yes you can specify other settings via `setLinearizeOptions` API

**Comment by arun3688** [comment] 2023-03-14 09:19
@MohammadHadiAlizadeh I think we should use this approach to simply avoid all the overhead for getting the matrix values, As we have support to generate linearized code in matlab format, we should simply use the generated matlab file and get all the necessary values needed, I did a small testing and it works very nice without much complications


```
addpath('C:/OPENMODELICAGIT/OpenModelica/testsuite/openmodelica/linearization/');
[A, B, C, D, stateVars, inputVars, outputVars] = linearized_model()

A =

   -2.8872   -1.6266
   -2.3809   -2.3884


B =

     0
     0


C =

     0     0


D =

    4.0075


stateVars =

    'num_x(1), num_x(2)'


inputVars =

    'u'


outputVars =

    'y'

```

And we can avoid all the overheads to just get these values,  and it will be very fast I guess, I will try to make changes in our code generation and try to push the changes, then you can test it until then you can try to use the fastLinearize() function

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-14 09:35
@arun3688 
Great!
That's an ingenious idea, and I guess it will work super fast!

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-14 10:04
@arun3688  @casella 
Do the ``-l`` flag and mos ``linearize()`` API follow an identical mathematical algorithm?
I can see a fairly considerable difference in the generated answers numerically.They return identical answers for small models. But when I tested both on an specific super-large model, I can see the result generated by the ``-l`` flag is ill-conditioned mathematically which is HIGHLY risky for any subsequent operation.

**Comment by arun3688** [comment] 2023-03-14 10:30
@MohammadHadiAlizadeh I guess i made a mistake with adding defaults -l = 0 which is wrong i guess, I have fixed that with this https://github.com/OpenModelica/OMMatlab/commit/dca6bfa2c9a77cc3da579ae32e263c3ca736c031 commit, can you pull the latest master and just try with old style 

```
omc.setLinearizationOptions(["stopTime=1"])
omc.linearize()
```

**Comment by casella** [comment] 2023-03-14 13:11
> @arun3688 @casella Do the `-l` flag and mos `linearize()` API follow an identical mathematical algorithm?

I thought so, but I'm not sure. Maybe @arun3688 can check on the source code.

Note that the required Jacobians can be computed analytically or numerically. For _simulation_ there is a compiler flag `--generateSymbolicJacobians` that activates the symbolic computation of Jacobians (doesn't always work). There is also a `-jacobian` simulation flag to influence which jacobian is used (defaults depend on the specific solver).

Again, I'm not sure how this is handled by the `-l` flag and by the `linearize()` API function, if @arun3688 could check, that would be great. Maybe the two methods differ in terms of flags activating the symbolic linearization.

> I can see a fairly considerable difference in the generated answers numerically.They return identical answers for small models. But when I tested both on an specific super-large model, I can see the result generated by the `-l` flag is ill-conditioned mathematically which is HIGHLY risky for any subsequent operation.

**Comment by casella** [comment] 2023-03-14 13:16
BTW, a small trick for linearization. Sometimes you have models that use mechanical connectors (which carry an angle), but the model actually doesn't use it, because all quantities depend on the velocity, not on the angle. This is the case with all kind of turbomachinery models, for example.

In these cases, you need to add equations such as `der(phi) = omega` to the model, which generate a non-reachable, non-observable part in the linearized model, _with eigenvalues in the origin_. This is not particularly nice from a numerical point of view, e.g. when computing the static gains, because you have a pole/zero cancellation exactly in the origin.

In these cases, I highly recommend to remove the row and column corresponding to these extra equations from the linearized system matrix, so you avoid numerical issues.

**Comment by arun3688** [comment] 2023-03-14 13:24
> Again, I'm not sure how this is handled by the `-l` flag and by the `linearize()` API function, if @arun3688 could check, that would be great.

The -l flag if set calls the linearize() function, It does the same thing what linearize() API does

**Comment by arun3688** [comment] 2023-03-14 14:06
@casella  @MohammadHadiAlizadeh I found the problem with the new approach by using the runtime flag `-l`, we do not set this command line option `setCommandLineOptions("generateSymbolicLinearization")` which gives different results and i discussed with adrian and it seems we cannot set the options directly on the simulation executable and we need to activate this option by using 

```
omc.sendExpression("setCommandLineOptions(""+generateSymbolicLinearization"")") // activate the command line Options
omc.buidModel(); // rebuild the model again 
omc.linearize() // this should work 
```
@MohammadHadiAlizadeh can you please try this i guess it should work. 

@casella, `-l ` is used just to avoid recompilation and speed up the process. The above operations are little bit advanced and a normal user does not want to do these things, they just want to use the linearize() API and get the results, So i guess i should add these command Line Options by default when user uses the following constructor

`ModelicaSystem(mod,"[BouncingBall.mo](http://bouncingball.mo/)","BouncingBall")`  and internally set all the commandLine Options needed for linearization regardless whether the user really performs the linearization or not, but when used it will speed up the process

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-14 15:13
@arun3688 

Getting the following error:

```

Error using eval
Unrecognized function or variable 'None'.

Error in OMMatlab/createcsvData (line 574)
                s1 = eval(replace(replace(replace(replace(var,"[","{"),"]","}"),"(","{"),")","}"));

Error in OMMatlab/linearize (line 764)
                obj.createcsvData(obj.linearOptions.('startTime'), obj.linearOptions.('stopTime'))

Error in Main_Matlab_Linearizer (line 12)
a=omc.linearize()% // this should work

```

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-14 15:14
[smp.zip](https://github.com/OpenModelica/OMMatlab/files/10970291/smp.zip)

This is the code

**Comment by arun3688** [comment] 2023-03-14 18:03
@MohammadHadiAlizadeh i looked into your code and it should be something like this 


```
import OMMatlab.*
omc= OMMatlab();
omc.ModelicaSystem("Eshgh.mo","Eshgh",["mid.mo"],"--generateSymbolicLinearization");

omc.setInputs("DMoraadi=0.99");
omc.setInputs("BMoraadi=0.99");
omc.setLinearizationOptions(["stopTime=1"]);
tic
a=omc.linearize()% // this should work 
```
I checked the generated `linearized_model.m` matlab code and the result looks good, see the attached zip file
[linearized_model.zip](https://github.com/OpenModelica/OMMatlab/files/10972225/linearized_model.zip)

**Comment by arun3688** [comment] 2023-03-14 20:53
@MohammadHadiAlizadeh All the issues are fixed with this commit https://github.com/OpenModelica/OMMatlab/commit/6bfef12a2e30911d7711abe5b6aeb426934ea713, Now the linearization process is extremely fast , With this changes the time taken to complete linearization is less than `5 seconds ` which is a good improvement. You will use the API as same before, no need to pass any new stuffs,  an example is 

```
omc=OMMatlab();
omc.ModelicaSystem("SCD_7.mo","SCD_7",["mid.mo"])
// set inputs, parameters etccc
omc.setLinearizationOption("stopTime=1")
omc.linearize()
```
For this speed up version you have to also download the latest openmodelica nighltly builds which will be available tomorrow (15-03-2023) from here https://openmodelica.org/download/nightlybuildsdownload/

I hope everything works for you as well

**Comment by MohammadHadiAlizadeh** [comment] 2023-03-15 09:07
Thanks. I'm closing the issue

**Closed as completed** 2023-03-15 09:07 UTC
