### ISSUE TITLE
incorrect order of names in linear states

### ISSUE THREAD

**Issue by MohammadHadiAlizadeh** [OpenModelica/OMMatlab#19] opened 2022-12-15 15:53 UTC
Hello,

I use the `linearize` command for the linearization of the following system:
```
der(x[1])= 4*x[1]+2*x[2]+3*x[3]+5*y1+3*u;   
der(x[2])= 1*x[2]+8*x[3]+2*y2;            
der(x[3])= x[3]+y1+2*y2;               
der(x[4])= x[4]+x[5]+y1+2*y2; 
der(x[5])= x[1]+x[6]+y1+3*y2; 
der(x[6])= x[2]+x[7]+y1+2*y2; 
der(x[7])= x[7]+x[8]+8*y1+2*y2; 
der(x[8])= x[10]+2*y2; 
der(x[9])= x[3]+x[9]+x[1]+y1+2*y2;   ///2x[3]
der(x[10])= x[1]+x[2]+x[3]+2*x[8]+12*y1+25*y2;
der(x[11])= 3*x[1]+a+x[8]+7*y1+2*y2+5*x[9]; 
der(a)= x[11]+x[10]+10*y1+2*y2;   

y1=x[1]+2*x[2]+a;
y2=x[3]+2+x[5]+x[8]; 
```

The linearization command works correctly. 
When I use `omc.getLinearStates()` it returns the following array:
`["a"	"x[10]"	"x[11]"	"x[1]"	"x[2]"	"x[3]"	"x[4]"	"x[5]"	"x[6]"	"x[7]"	"x[8]"	"x[9]"]`

However, the order of the state variable names is as the following in the linearized.mo file :
```
  Real 'x_a' = x[1];
  Real 'x_x[1]' = x[2];
  Real 'x_x[2]' = x[3];
  Real 'x_x[3]' = x[4];
  Real 'x_x[4]' = x[5];
  Real 'x_x[5]' = x[6];
  Real 'x_x[6]' = x[7];
  Real 'x_x[7]' = x[8];
  Real 'x_x[8]' = x[9];
  Real 'x_x[9]' = x[10];
  Real 'x_x[10]' = x[11];
  Real 'x_x[11]' = x[12];
```
Please consider that the A, B, C, and D matrices are the same in both the linearized file and the result of the `linearize` command.

For advanced control problems like MPC, it is necessary for the resulting state names order to be as same as the order in linearized.mo file. Because it is difficult to check the correct state name order in each iteration( there is a possibility of introducing new states to the model due to the hybrid form of the system).

The same bug is possible for these commands too:
```
omc.getLinearOutputs()
omc.getLinearInputs()
```

the supplementary files:
[test.zip](https://github.com/OpenModelica/OMMatlab/files/10238509/test.zip)

Thanks for your help

**Comment by MohammadHadiAlizadeh** [comment] 2022-12-21 12:56
@kabdelhak can you please help?

**Comment by MohammadHadiAlizadeh** [comment] 2022-12-21 12:57
@arun3688  do you have any idea why this happens?

**Comment by arun3688** [comment] 2022-12-21 13:02
@MohammadHadiAlizadeh I am currently little busy with other works, I will have time tomorrow and i can look into the issue

**Comment by MohammadHadiAlizadeh** [comment] 2022-12-22 14:18
@arun3688 many thanks

**Comment by casella** [comment] 2022-12-22 22:35
@MohammadHadiAlizadeh I'm sorry, I thought I had answered to this already, apparently I did not click the "comment" button.

The problem here is that the generated code orders the states lexicographically. Hence, as you can see from `omc.getLinearStates()`, you first get `x[10]`, then `x[11]`, then `x[1]`, because `0` comes before `1`, which comes before `]` in the ASCII table.

I'm not sure how the variables are ordered in the Matlab output, but I guess this should also use lexicographical ordering, to match what the backend does.

**Comment by MohammadHadiAlizadeh** [comment] 2022-12-23 05:50
@casella , thanks for your explanation.
I see. The main problem is the order mismatch between the variables in linearized.mo file(generated from linearization process) and the strings from``omc.getLinearStates``. As the A, B, C, and D matrices are the same.

However, when using 11x scalar values instead of an array like ( ``x1,x2....,x11`` instead of `` x[1],x[2],.....x[11]``), the orders in both linearized.mo (resulting from linearization command) file and ``omc.getLinearStates`` are the same and lexicographical(`` x10 x11 x1 ...``).

**Comment by casella** [comment] 2022-12-23 16:56
It could be that linearized.mo tries to play smart and orders the array elements properly, instead of doing that lexicographically. Unfortunately that's not a good idea. In fact, it may be better to order the states in the generated code in the proper way, when arrays are concerned, but this could be non-trivial in some cases, e.g. multi-dimensional arrays, sliced arrays etc.

In any case, I would suggest that the linearize method uses the same order of the generated code, whatever it is.

**Comment by arun3688** [comment] 2023-01-02 04:15
@MohammadHadiAlizadeh @casella the reason behind this ordering is due to the generated `linearized_model_init.xml`. The xml file has the following ordering

  ```
<ScalarVariable
    name = "&#39;x_a&#39;"
    valueReference = "1223"
    variability = "continuous" isDiscrete = "false"
    causality = "local" isValueChangeable = "false"
    alias = "alias" aliasVariable="x[1]" aliasVariableId="0"
    classIndex = "1" classType = "rAli"
    isProtected = "false" hideResult = ""
    fileName = "C:/Users/arupa54/AppData/Local/Temp/tp0ad609a8_321a_428f_bb2c_22233bee56ad/linearized_model.mo" startLine = "49" startColumn = "3" endLine = "49" endColumn = "20" fileWritable = "true">
    <Real fixed="false" useNominal="false" />
  </ScalarVariable>
  <ScalarVariable
    name = "&#39;x_x[10]&#39;"
    valueReference = "1224"
    variability = "continuous" isDiscrete = "false"
    causality = "local" isValueChangeable = "false"
    alias = "alias" aliasVariable="x[11]" aliasVariableId="10"
    classIndex = "2" classType = "rAli"
    isProtected = "false" hideResult = ""
    fileName = "C:/Users/arupa54/AppData/Local/Temp/tp0ad609a8_321a_428f_bb2c_22233bee56ad/linearized_model.mo" startLine = "59" startColumn = "3" endLine = "59" endColumn = "25" fileWritable = "true">
    <Real fixed="false" useNominal="false" />
  </ScalarVariable>
  <ScalarVariable
    name = "&#39;x_x[11]&#39;"
    valueReference = "1225"
    variability = "continuous" isDiscrete = "false"
    causality = "local" isValueChangeable = "false"
    alias = "alias" aliasVariable="x[12]" aliasVariableId="11"
    classIndex = "3" classType = "rAli"
    isProtected = "false" hideResult = ""
    fileName = "C:/Users/arupa54/AppData/Local/Temp/tp0ad609a8_321a_428f_bb2c_22233bee56ad/linearized_model.mo" startLine = "60" startColumn = "3" endLine = "60" endColumn = "25" fileWritable = "true">
    <Real fixed="false" useNominal="false" />
  </ScalarVariable>
  <ScalarVariable
    name = "&#39;x_x[1]&#39;"
    valueReference = "1226"
    variability = "continuous" isDiscrete = "false"
    causality = "local" isValueChangeable = "false"
    alias = "alias" aliasVariable="x[2]" aliasVariableId="1"
    classIndex = "4" classType = "rAli"
    isProtected = "false" hideResult = ""
    fileName = "C:/Users/arupa54/AppData/Local/Temp/tp0ad609a8_321a_428f_bb2c_22233bee56ad/linearized_model.mo" startLine = "50" startColumn = "3" endLine = "50" endColumn = "23" fileWritable = "true">
    <Real fixed="false" useNominal="false" />
  </ScalarVariable>
```
when exporting to `_init.xml` , the variables are not sorted and i hope the sorting is not important for the xml, but i see there is an `aliasVariableId` which should be used and sort the array when using the API in `OMMatlab` or we should directly fix in the `_init.xml` ?

**Comment by MohammadHadiAlizadeh** [comment] 2023-01-02 07:18
@arun3688 , Maybe it is a good idea to change OMMatlab. Since the problem occurs when using array expressions in the Model, while the scalar variable has an identical name ordering in `` _linearized.mo`` and getLinearStates/getLinearSOutputs result.

**Comment by casella** [comment] 2023-01-02 17:12
@arun3688 I'm not sure what is the role of the alias variable names in this xml, since I can't see any reference to _state variables_ in there.  I don't know where OMMatlab takes the information of who are the state variables in the generated code; wherever this information comes from, we should use it as it is and avoid trying to apply any further ordering to it.

**Comment by arun3688** [comment] 2023-01-02 17:34
@casella when the linearized model is created we identify the states, input and output variables with the following notations

```
states = x_
inputs = u_
outputs = y_ 
```
and in the linearized model you can see the following declaration of variables

 ```
 Real 'x_a' = x[1];
  Real 'x_x[1]' = x[2];
  Real 'x_x[2]' = x[3];
  Real 'x_x[3]' = x[4];
  Real 'x_x[4]' = x[5];
  Real 'x_x[5]' = x[6];
  Real 'x_x[6]' = x[7];
  Real 'x_x[7]' = x[8];
  Real 'x_x[8]' = x[9];
  Real 'x_x[9]' = x[10];
  Real 'x_x[10]' = x[11];
  Real 'x_x[11]' = x[12];
  Real 'u_u' = u[1];
  Real 'y_y1' = y[1];
  Real 'y_y2' = y[2];
```
And from the _init.xml, I parse the scalar variables to get the states, inputs and outputs and in the xml you can see the order differs

**Comment by arun3688** [comment] 2023-01-03 14:12
@MohammadHadiAlizadeh The issue is fixed with this commit https://github.com/OpenModelica/OMMatlab/commit/3b011e7790f68b04e9308eb6e21036cac2d42322, Now we can get correct ordering of index

```
>> omc.getLinearStates()

ans = 

  1×12 string array

  Columns 1 through 10

    "a"    "x[1]"    "x[2]"    "x[3]"    "x[4]"    "x[5]"    "x[6]"    "x[7]"    "x[8]"    "x[9]"

  Columns 11 through 12

    "x[10]"    "x[11]"
```

pull the changes from the latest master and test it

**Comment by MohammadHadiAlizadeh** [comment] 2023-01-03 15:00
@arun3688, Thank you so much. It works well. I'm closing this issue as it finished.

**Closed as completed** 2023-01-03 15:00 UTC
