### ISSUE TITLE
Problem when using setParametrs+Linearization

### ISSUE THREAD

**Issue by MohammadHadiAlizadeh** [OpenModelica/OMMatlab#21] opened 2022-12-22 19:09 UTC
Hi

When trying to set initial states from upstream with set parameters, the Linearization command does not consider the upstream specified parameter values.
For example, consider the model
```mo
model test7
  Real[2] x;
  parameter Real[2] x_PI;
  input Real u;
initial equation
  x=x_PI;
equation
  der(x[1])=x[1]^2+u;
  der(x[2])=x[2]^3;
end test7;
```

Matlab command:
```matlab
clear all
import OMMatlab.*
global fie

omc=OMMatlab();

omc.ModelicaSystem("test7.mo","test7");

omc.setInputs("u=2");

omc.setParameters("x_PI_1_=2");
omc.setParameters("x_PI_2_=3");

omc.setLinearizationOptions(["startTime=0","stopTime=0"])%"stepSize=0.0001","tolerance=1e-05"])% 
a=omc.linearize()

A=cell2mat(a(1));
```
It considers the initial condition as [0;0] , and returns the A=[0 0;0 0], while I set the initial values as [2;3] and it is supposed for A to be [4 0;0 27]

**Comment by MohammadHadiAlizadeh** [comment] 2022-12-22 19:18
However, when I use 2x scalar parameters instead of a vector of 2 by 1, As:

```mo
model test7
  Real[2] x;
  parameter Real x_P1;
  parameter Real x_P2;
  input Real u;
initial equation
  x[1]=x_P1;
  x[2]=x_P2;
equation
  der(x[1])=x[1]^2+u;
  der(x[2])=x[2]^3;
end test7;
```
```matlab
clear all
import OMMatlab.*
global fie

omc=OMMatlab();

omc.ModelicaSystem("test7.mo","test7");

omc.setInputs("u=2");

omc.setParameters("x_P1=2");
omc.setParameters("x_P2=3");

omc.setLinearizationOptions(["startTime=0","stopTime=0"])%"stepSize=0.0001","tolerance=1e-05"])% 
a=omc.linearize()

A=cell2mat(a(1));
```

it returns A=[4 0;0 27] that is correct!

Am I doing something wrong when using vector parameters?

**Comment by MohammadHadiAlizadeh** [comment] 2023-01-02 07:19
@arun3688 , can you please investigate this issue too?

**Comment by arun3688** [comment] 2023-01-02 08:11
@MohammadHadiAlizadeh sure

**Comment by arun3688** [comment] 2023-01-02 08:49
@MohammadHadiAlizadeh This issue is fixed with your commit https://github.com/OpenModelica/OMMatlab/commit/88dda46147e92dc1d98730dd694f349b3f8eee81. It is a parse Error thanks for the fix

**Comment by arun3688** [comment] 2023-01-02 11:36
@MohammadHadiAlizadeh I did testing on your first scenario with the settings you provided and i get the following error message

```
>> omc.setInputs("u=2")
>> omc.setParameters("x_PI_1_=2")
>> omc.setParameters("x_PI_2_=3")
>> omc.simulate()
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
DASKR--  AT T (=R1) AND STEPSIZE H (=R2) THE                                    
      In above,  R1 =   5.5554441283221E-02   R2 =   2.1521548367686E-17
DASKR--  ERROR TEST FAILED REPEATEDLY OR WITH ABS(H)=HMIN                       
stdout            | warning | DDASSL had repeated error test failures on the last attempted step.
stdout            | warning | can't continue. time = 0.055554
stdout            | info    | model terminate | Integrator failed. | Simulation terminated at time 0.0555544

ans =

    -7

>> 
```

But if i don't do any kind of setting then the model works, I did a small testing on the model below to make sure setting states from upstream parameters and this worked

```
model test7
  parameter Real[1] x;
  Real [1] a;
  input Real u;
initial equation
  a = x;
equation
  der(a[1]) = u;
end test7;
```

**Comment by MohammadHadiAlizadeh** [comment] 2023-01-02 13:35
@arun3688 , The simulation failed because I used an arbitrary example.
please consider the following cases:

- **First case: Two scalar parameters used to specify Initial values**

   _Open Modelica Model:_

```
model test7
  Real[2,1] x;
  parameter Real x_P1;
  parameter Real x_P2;
  input Real u;
initial equation
  x[1,1]=x_P1;
  x[2,1]=x_P2;
equation
  der(x[1,1])=x[1,1]^0.1+u;
  der(x[2,1])=x[2,1]^0.1;
end test7;
```
_Matlab Script_

```
clear all
import OMMatlab.*


omc=OMMatlab();

omc.ModelicaSystem("test7.mo","test7");

omc.setInputs("u=2");

omc.setParameters("x_P1=2");
omc.setParameters("x_P2=3");
 omc.setLinearizationOptions(["startTime=0","stopTime=0"])

a=omc.linearize()

A=cell2mat(a(1))
```

Returns A=[0.053 0;0 0.037]  which is _true_ value.


- **Second case: One array parameter[2,1] used to specify Initial values**
     _Open Modelica Model:_

```
model test7
  Real[2,1] x;
  parameter Real[2,1] x_PI;
  input Real u;
initial equation
  x=x_PI;
equation
  der(x[1,1])=x[1,1]^0.1+u;
  der(x[2,1])=x[2,1]^0.1;
end test7
```
_Matlab script:_

```
clear all
import OMMatlab.*


omc=OMMatlab();

omc.ModelicaSystem("test7.mo","test7");

omc.setInputs("u=2");

omc.setParameters("x_PI_1_1_=2");
omc.setParameters("x_PI_2_1_=3");
 omc.setLinearizationOptions(["startTime=0","stopTime=0"])

a=omc.linearize()

A=cell2mat(a(1))
```
Specifies [0,0] to the initial values instead of [2,3] , and fails(because of division by zero)
```
Warning: Parameter x_PI[2,1] has no value, and is fixed during initialization (fixed=true), using available start value (start=0.0) as default value.
Warning: Parameter x_PI[1,1] has no value, and is fixed during initialization (fixed=true), using available start value (start=0.0) as default value.
```

The main problem is with Linearization. Simulation works correctly.

**Comment by MohammadHadiAlizadeh** [comment] 2023-01-02 13:40
Reg. Linearization options, I used``["startTime=0","stopTime=0"]``, because it is mentioned in the UG the following procedure to get the matrices at the initial point

_"This function initializes a Modelica model and then simulates the model with its default experiment options until time instant "t_linearize". If t_linearize=0, no simulation takes place (only initialization)."_
[link](https://build.openmodelica.org/Documentation/Modelica_LinearSystems2.Utilities.Import.linearize.html)

**Comment by arun3688** [comment] 2023-01-02 13:44
@MohammadHadiAlizadeh the scenario two is not working right ?

**Comment by MohammadHadiAlizadeh** [comment] 2023-01-02 13:50
@arun3688 , yes. It does not consider the specified initial values and specifies 0 instead. Therefore, it returns a wrong value for matrices, or fails because of division by zero depending on the form of mathematical functions.

**Comment by MohammadHadiAlizadeh** [comment] 2023-01-03 15:03
@arun3688, 
Regarding this issue, I guess it happens because there is a problem with overriding array parameter elements by new specified values when using Linearize command. I would appreciate your help if you could look into it.

**Comment by arun3688** [comment] 2023-01-04 13:46
@MohammadHadiAlizadeh The issue is fixed with this commit https://github.com/OpenModelica/OMMatlab/commit/6fff276a52864addf9448dffb50743e6b60a0c8b, the problem is due to array variables are not mapped back to their original names and hence the issue, I have tested your example and it gives the correct results

```
>> res = omc.linearize()
>> res{1}
ans =
     4     0
     0    27
```
Pull the latest master and test it.

**Comment by MohammadHadiAlizadeh** [comment] 2023-01-04 14:38
@arun3688 , Thank you. It's working now.

**Closed as completed** 2023-01-04 14:38 UTC
